---
  - hosts: all
    vars_files: ../defaults/main.yml
    tasks:
        
      - name: Create user
        user:
          name: "{{ user }}"
          password: "{{ password | password_hash('sha512') }}"
          shell: /bin/bash
          state: present
        become: true

      - name: Adding user to sudoers
        template:
          src: ../templates/sudo_user.j2
          dest: /etc/sudoers.d/exacs
          mode: 0440
          owner: root
          group: root
        become: true

      - name: create jumpbox script
        template:
          src: ../templates/jumpbox-vmresize
          dest: /usr/local/sbin/jumpbox-vmresize
          mode: 0755
          owner: root
          group: staff
        become: true

      - name: create VM resize script
        template:
          src: ../templates/resize
          dest: /usr/bin/resize
          mode: 0755
          owner: root
          group: root
        become: true

      - name: update user .bashrc
        template:
          src: ../templates/user-bashrc
          dest: /home/exacs/.bashrc
          mode: 0644
          owner: exacs
          group: exacs
          
