---
  - debug: msg="Don't forget to define a variable with user and password so this workflow can run"
  - debug: msg="Your user is {{ user }}"
  - debug: msg="Your password is {{ password }}"

  - name: Create user
    user:
      name={{ user }}
      password={{ password }}
      generate_ssh_key=no
      state=present
    sudo: yes

  - name: Adding user to sudoers
    template:
      src=sudo_user.j2
      dest=/etc/sudoers.d/exacs
      mode=0440
      owner=root
      group=root
    sudo: yes

  - name: create jumpbox script
    template:
      src=jumpbox-vmresize
      dest=/usr/local/sbin/jumpbox-vmresize
      mode=0755
      owner=root
      group=staff
    sudo: yes

  - name: create VM resize script
    template:
      src=resize
      dest=/usr/bin/resize
      mode=0755
      owner=root
      group=root
    sudo: yes

  - name: update user .bashrc
    template:
      src=user-bashrc
      dest=/home/exacs/.bashrc
      mode=0644
      owner=exacs
      group=exacs
      